# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Red teaming configuration

# Docs: https://promptfoo.dev/docs/red-team/configuration
description: "My first red team"

providers:
  - id: 'file://send_redteam.py'


# Other redteam settings
redteam:
  purpose: "Travel agent specializing in developing customized itineraries for 7-day trips to Florence, Italy"

  # Default number of inputs to generate for each plugin.
  # The total number of tests will be (numTests * plugins.length * (1 + strategies.length))
  numTests: 5

  # Each plugin generates 5 adversarial inputs.
  # To control the number of tests for each plugin, use:
  # - id: plugin-name
  #   numTests: 10
  plugins:
    - default  # Includes common plugins
    - harmful  # All harmful categories
    - pii  # All PII categories
    - contracts  # Enters business or legal commitments without supervision
    - cross-session-leak  # Checks for information sharing between unrelated sessions
    - excessive-agency  # Model taking excessive initiative or misunderstanding its capabilities
    - hallucination  # Model generating false or misleading information
    - hijacking  # Unauthorized or off-topic resource use
    - overreliance  # Model susceptible to relying on an incorrect user assumption or input
    - politics  # Makes political statements
    - harmful:child-exploitation  # Content exploiting or harming children
    - harmful:hate  # Content that promotes hate or discrimination
    - harmful:indiscriminate-weapons  # Content related to weapons without context
    - harmful:non-violent-crime  # Content related to non-violent criminal activities
    - harmful:self-harm  # Content that encourages self-harm or suicide
    - harmful:sex-crime  # Content related to sexual crimes
    - harmful:sexual-content  # Explicit or inappropriate sexual content
    - harmful:violent-crime  # Content related to violent criminal activities
    - harmful:chemical-biological-weapons  # Content related to chemical or biological weapons
    - harmful:copyright-violations  # Content violating copyright laws
    - harmful:cybercrime  # Content related to cybercriminal activities
    - harmful:graphic-content  # Displaying graphic or violent content
    - harmful:harassment-bullying  # Content that harasses or bullies individuals
    - harmful:illegal-activities  # Content promoting illegal activities
    - harmful:illegal-drugs  # Content related to illegal drug use or trade
    - harmful:unsafe-practices  # Content promoting unsafe or harmful practices
    - harmful:insults  # Content that insults or demeans individuals
    - harmful:profanity  # Content containing profane or inappropriate language
    - harmful:radicalization  # Content that promotes radical or extremist views
    - harmful:intellectual-property  # Content violating intellectual property rights
    - harmful:misinformation-disinformation  # Spreading false or misleading information
    - harmful:privacy  # Content violating privacy rights
    - harmful:specialized-advice  # Providing advice in specialized fields without expertise
    - pii:api-db  # PII exposed through API or database
    - pii:direct  # Direct exposure of PII
    - pii:session  # PII exposed in session data
    - pii:social  # PII exposed through social engineering
    - rbac  # Tests whether the model properly implements Role-Based Access Control (RBAC)
    - bola  # Broken Object Level Authorization (BOLA) tests
    - bfla  # Broken Function Level Authorization (BFLA) tests
    - ssrf  # Server-Side Request Forgery (SSRF) tests

  # Attack methods for applying adversarial inputs
  strategies:
    - jailbreak # Attempts to bypass security measures through iterative prompt refinement
    - prompt-injection # Malicious inputs designed to manipulate the model's behavior

  evaluateOptions:
    - maxConcurrency: 10
